### ISSUE TITLE
[Bug] Duplicate of usage command

### ISSUE THREAD

**Issue by Aju100** [naryal2580/shebang#1]
Hey @naryal2580,

Labeling of uninstalling command in the usage should be fixed as the user might be confused and ended up using reinstall one.
### Steps to reproduce
- clone the repo and run the script
```sh
./main.sh
```
### Output:
![unin](https://user-images.githubusercontent.com/29862610/117996946-4c1bf680-b362-11eb-81b0-efa1d70f7c74.png)

### Patch
```sh
h|-h|--help|help|"")
		banner
		printf "\nInstall 5h3_b4nG:\n"
		echo "    ./main.sh --install"
		printf "\nRe-install 5h3_b4nG:\n"
		echo "    ./main.sh --reinstall"
		printf "\nUninstall 5h3_b4nG:\n"
		echo "    ./main.sh --uninstalll"

	;;
```

**Comment by naryal2580** [comment]
Nice catch, fixing it right from the browser!
